# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appliances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='appliance',
            unique_together=set([('name', 'owner')]),
        ),
    ]
