# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0002_auto_20170303_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='authentication_model',
            field=models.CharField(choices=[('token', 'Token')], default='token', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliance',
            name='authentication_value',
            field=models.CharField(default='x', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliance',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reading',
            name='appliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='appliances.Appliance'),
        ),
    ]
