# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 10:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0004_auto_20170305_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='day',
            field=models.IntegerField(default=0, validators=(django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31))),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='hour',
            field=models.IntegerField(default=0, validators=(django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23))),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='microsecond',
            field=models.IntegerField(default=0, validators=(django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999))),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='minute',
            field=models.IntegerField(default=0, validators=(django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59))),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='month',
            field=models.IntegerField(default=1, validators=(django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12))),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='second',
            field=models.IntegerField(default=0, validators=(django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59))),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='year',
            field=models.IntegerField(default=2010, validators=(django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999))),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
