# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0005_auto_20170306_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='authentication_model',
            field=models.CharField(choices=[('token', 'Token'), ('gcm_aes', 'GCM + AES128')], max_length=16),
        ),
    ]
