# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:48
from __future__ import unicode_literals

import appliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0009_auto_20170404_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='authentication_value',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[appliances.models.validate_256bit_or_more_b64_string]),
        ),
    ]
