# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 19:14
from __future__ import unicode_literals

import appliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0010_auto_20170404_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='authentication_model',
            field=models.CharField(choices=[('token', 'Token'), ('sha_hmac', 'SHA256 HMAC')], max_length=16),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='authentication_value',
            field=models.CharField(blank=True, default='', max_length=64, validators=[appliances.models.validate_256bit_or_more_b64_string]),
        ),
    ]
