# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appliances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('appliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='appliances.Appliance')),
            ],
        ),
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='appliances.Reading')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensors.Sensor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sensorvalue',
            unique_together=set([('sensor', 'reading')]),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together=set([('code', 'appliance'), ('name', 'appliance')]),
        ),
    ]
