# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20170303_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
